In [11]:
import pandas as pd

df = pd.read_csv("data.csv")
df.head()

                                               title  score  comments
0      GameStop makes $55.5B takeover offer for eBay    187       122
1  ASML's Best Selling Product Isn't What You Thi...     45        22
2        Trademark violation: Fake Notepad++ for Mac    234        98
3  Using “underdrawings” for accurate text and nu...    271        92
4  Texico: Learn the principles of programming wi...     75         4

In [12]:
# Clean the text
df["title"] = df["title"].str.lower()

# Create labels
threshold = df["score"].quantile(0.7)           # We will consider the top 30% scored posts as positive, instead of using a fixed arbitrary threshold
df["label"] = (df["score"] > threshold).astype(int)

# Selecting only what we need
df = df[["title", "label"]]
df.head()

                                               title  label
0      gamestop makes $55.5b takeover offer for ebay      0
1  asml's best selling product isn't what you thi...      0
2        trademark violation: fake notepad++ for mac      0
3  using “underdrawings” for accurate text and nu...      1
4  texico: learn the principles of programming wi...      0

In [13]:
# Save new csv

df.to_csv("clean_data.csv", index=False)